YuraRov/vetClinicFrontEnd

- src/app/app.component.html
- src/app/app.component.sass
- src/app/app.module.ts
- src/app/core/models/Address.ts
- src/app/core/models/User.ts
- src/app/core/services/addressService/address.service.spec.ts
- src/app/core/services/addressService/address.service.ts
- src/app/core/services/userService/user.service.spec.ts
- src/app/core/services/userService/user.service.ts
- src/app/layout/footer/footer.component.sass
- src/app/shared/components/userComponents/delete-user/delete-user.component.html
- src/app/shared/components/userComponents/delete-user/delete-user.component.sass
- src/app/shared/components/userComponents/delete-user/delete-user.component.spec.ts
- src/app/shared/components/userComponents/delete-user/delete-user.component.ts
- src/app/shared/components/userComponents/edit-user/edit-user.component.html
- src/app/shared/components/userComponents/edit-user/edit-user.component.sass
- src/app/shared/components/userComponents/edit-user/edit-user.component.spec.ts
- src/app/shared/components/userComponents/edit-user/edit-user.component.ts
- src/app/shared/components/userComponents/user-profile-info/user-profile-info.component.html
- src/app/shared/components/userComponents/user-profile-info/user-profile-info.component.sass
- src/app/shared/components/userComponents/user-profile-info/user-profile-info.component.spec.ts
- src/app/shared/components/userComponents/user-profile-info/user-profile-info.component.ts
- src/app/shared/components/userComponents/users/users.component.html
- src/app/shared/components/userComponents/users/users.component.sass
- src/app/shared/components/userComponents/users/users.component.spec.ts
- src/app/shared/components/userComponents/users/users.component.ts
- src/app/shared/shared.module.ts
Created user, profile info, edit and delete forms
> Created user, profile info, edit and delete forms

- src/app/shared/components/userComponents/create-employee/create-employee.component.html
- src/app/shared/components/userComponents/create-employee/create-employee.component.sass
- src/app/shared/components/userComponents/create-employee/create-employee.component.spec.ts
- src/app/shared/components/userComponents/create-employee/create-employee.component.ts
- src/app/shared/components/userComponents/users/users.component.ts
- src/app/shared/shared.module.ts
Created employee registration functionality
> Created employee registration functionality

- src/app/core/models/RegisterEmployeeModel.ts
- src/app/core/models/User.ts
- src/app/core/services/resourceService/resource.service.ts
- src/app/core/services/userService/user.service.ts
- src/app/shared/components/userComponents/create-employee/create-employee.component.html
- src/app/shared/components/userComponents/create-employee/create-employee.component.sass
- src/app/shared/components/userComponents/create-employee/create-employee.component.ts
- src/app/shared/components/userComponents/doctors/doctors.component.html
- src/app/shared/components/userComponents/doctors/doctors.component.sass
- src/app/shared/components/userComponents/doctors/doctors.component.ts
Changed Doctors page, edited employee registration
> Changed Doctors page, edited employee registration

- src/app/core/services/userService/user.service.ts
- src/app/layout/footer/footer.component.sass
- src/app/layout/header/header.component.html
- src/app/shared/components/userComponents/create-employee/create-employee.component.html
- src/app/shared/components/userComponents/create-employee/create-employee.component.sass
- src/app/shared/components/userComponents/create-employee/create-employee.component.ts
- src/app/shared/components/userComponents/doctors/doctors.component.ts
- src/app/shared/components/userComponents/users/users.component.html
- src/app/shared/components/userComponents/users/users.component.sass
- src/app/shared/components/userComponents/users/users.component.ts
Changed doctors retrieval logic, edited styles
> Changed doctors retrieval logic, edited styles

- src/app/core/services/userService/user.service.ts
- src/app/layout/footer/footer.component.html
- src/app/layout/footer/footer.component.sass
- src/app/shared/components/userComponents/create-employee/create-employee.component.ts
- src/app/shared/components/userComponents/delete-user/delete-user.component.html
- src/app/shared/components/userComponents/delete-user/delete-user.component.ts
- src/app/shared/components/userComponents/doctors/doctors.component.html
- src/app/shared/components/userComponents/doctors/doctors.component.sass
- src/app/shared/components/userComponents/doctors/doctors.component.ts
- src/app/shared/components/userComponents/edit-user/edit-user.component.html
- src/app/shared/components/userComponents/edit-user/edit-user.component.ts
- src/app/shared/components/userComponents/user-profile-info/user-profile-info.component.ts
- src/app/shared/components/userComponents/users/users.component.ts
Edited doctors page, made small code changes in other files
> Edited doctors page, made small code changes in other files

- src/app/app.component.ts
- src/app/core/models/RegisterEmployeeModel.ts
- src/app/core/models/User.ts
- src/app/core/services/userService/user.service.ts
- src/app/shared/components/userComponents/create-employee/create-employee.component.ts
- src/app/shared/components/userComponents/doctors/doctors.component.html
- src/app/shared/components/userComponents/doctors/doctors.component.ts
- src/app/shared/components/userComponents/edit-user/edit-user.component.ts
- src/app/shared/components/userComponents/users/users.component.html
- src/app/shared/components/userComponents/users/users.component.sass
> Made small code edits

- src/app/app.module.ts
- src/app/core/models/Employees.ts
- src/app/core/services/financialService/employee.service.ts
- src/app/layout/header/header.component.html
- src/app/shared/components/financeComponents/new-salary-dialog/new-salary-dialog.component.html
- src/app/shared/components/financeComponents/new-salary-dialog/new-salary-dialog.component.ts
- src/app/shared/components/financeComponents/salary-page/salary-page.component.ts
also salarypage is only for accountant now
> use User model instead employees

- src/app/core/services/userService/user.service.ts
- src/app/shared/components/userComponents/doctors/doctors.component.ts
Edited doctors filtration logic
> Edited doctors filtration logic

- src/app/core/models/User.ts
- src/app/shared/components/userComponents/doctors/doctors.component.html
- src/app/shared/components/userComponents/doctors/doctors.component.sass
- src/app/shared/components/userComponents/doctors/doctors.component.ts
Edited User profile, specializations types
> Edited User profile, specializations types

- src/app/core/models/RegisterEmployeeModel.ts
- src/app/core/models/User.ts
- src/app/shared/components/userComponents/create-employee/create-employee.component.html
- src/app/shared/components/userComponents/create-employee/create-employee.component.sass
- src/app/shared/components/userComponents/create-employee/create-employee.component.ts
- src/app/shared/components/userComponents/doctors/doctors.component.html
- src/app/shared/components/userComponents/doctors/doctors.component.sass
- src/app/shared/components/userComponents/edit-user/edit-user.component.html
- src/app/shared/components/userComponents/edit-user/edit-user.component.sass
- src/app/shared/components/userComponents/edit-user/edit-user.component.ts
- src/app/shared/components/userComponents/user-profile-info/user-profile-info.component.html
- src/app/shared/components/userComponents/user-profile-info/user-profile-info.component.sass
Created user's profile picture functionality
> Created user's profile picture functionality

- src/app/shared/components/userComponents/create-employee/create-employee.component.ts
Changed double quotes to single
> Changed double quotes to single

- src/app/features/doctors/doctors.component.ts
- src/app/features/doctors/doctors.module.ts
- src/app/features/userDashboard/components/create-employee/create-employee.component.ts
- src/app/features/userDashboard/components/delete-user/delete-user.component.ts
- src/app/features/userDashboard/components/users/users.component.ts
- src/app/features/userDashboard/services/userService/user.service.ts
- src/app/features/userDashboard/user-dashboard-routing.module.ts
- src/app/features/userDashboard/user-dashboard.module.ts
Removed unnecessary body header in service
> Removed unnecessary body header in service

- src/app/features/userProfile/components/user-profile-edit/user-base-edit.component.ts
- src/app/features/userProfile/components/user-profile-info/user-profile-info.component.ts
- src/app/features/userProfile/user-profile-routing.module.ts
- src/app/features/userProfile/user-profile.module.ts
> Added spaces to imports

- src/app/features/userProfile/components/user-profile-edit/user-base-edit.component.html
- src/app/features/userProfile/components/user-profile-edit/user-base-edit.component.ts
Made profile picture url on user edit safe
> Made profile picture url on user edit safe

- src/app/features/doctors/doctors.component.html
- src/app/features/doctors/doctors.component.ts
- src/app/features/userProfile/components/user-profile-edit/user-base-edit.component.html
- src/app/features/userProfile/components/user-profile-edit/user-base-edit.component.ts
- src/app/features/userProfile/components/user-profile-info/user-profile-info.component.html
- src/app/features/userProfile/components/user-profile-info/user-profile-info.component.ts
Made profile pictures' url safe in views
> Made profile pictures' url safe in views

- src/app/features/userDashboard/components/users/users.component.html
- src/app/features/userDashboard/components/users/users.component.sass
- src/app/features/userDashboard/components/users/users.component.ts
- src/app/features/userDashboard/services/userService/user.service.ts
- src/app/features/userDashboard/user-dashboard.module.ts
Added pagination to users.component
> Added pagination to users.component

- src/app/features/doctors/doctors.component.html
- src/app/features/userDashboard/components/create-employee/create-employee.component.html
- src/app/features/userDashboard/components/create-employee/create-employee.component.ts
- src/app/features/userDashboard/components/users/users.component.html
- src/app/features/userDashboard/components/users/users.component.ts
- src/app/features/userDashboard/services/userService/user.service.ts
- src/app/features/userProfile/components/user-profile-edit/user-base-edit.component.html
- src/app/features/userProfile/components/user-profile-edit/user-base-edit.component.sass
- src/app/features/userProfile/components/user-profile-edit/user-base-edit.component.ts
- src/app/features/userProfile/components/user-profile-info/user-profile-info.component.html
Changed front-end for new profile picture logic
> Changed front-end for new profile picture logic

- src/app/core/models/RegisterEmployeeModel.ts
- src/app/core/models/User.ts
- src/app/features/userDashboard/components/create-employee/create-employee.component.html
- src/app/features/userDashboard/components/create-employee/create-employee.component.ts
Changed default profile picture logic
> Changed default profile picture logic

- src/app/features/userDashboard/components/users/users.component.html
- src/app/features/userDashboard/components/users/users.component.sass
- src/app/features/userDashboard/components/users/users.component.ts
- src/app/features/userDashboard/services/userService/user.service.ts
> Added orderBy functionality

- src/app/features/userProfile/components/user-profile-edit/user-base-edit.component.html
- src/app/features/userProfile/components/user-profile-edit/user-base-edit.component.ts
- src/app/features/userProfile/components/user-profile-info/user-profile-info.component.html
- src/app/features/userProfile/components/user-profile-info/user-profile-info.component.ts
Made small changes regarding user profile pictures
> Made small changes regarding user profile pictures

- src/app/features/doctors/doctors.component.html
- src/app/features/doctors/doctors.component.sass
- src/app/features/doctors/doctors.component.ts
- src/app/features/userProfile/components/user-profile-edit/user-base-edit.component.html
- src/app/features/userProfile/components/user-profile-edit/user-base-edit.component.ts
> Made small changes

- src/app/features/userDashboard/services/userService/user.service.ts
- src/app/features/userProfile/components/user-profile-edit/user-base-edit.component.ts
- src/app/features/userProfile/components/user-profile-info/user-profile-info.component.ts
- src/app/features/userProfile/user-profile.module.ts
- src/app/layout/header/header.component.ts
Added edit subject to user-service
> Added edit subject to user-service

- src/app/features/exceptions/components/exception-page/exception-page.component.html
- src/app/features/exceptions/components/exception-page/exception-page.component.ts
- src/app/features/exceptions/components/exception-stats-page/exception-stats-page.component.html
- src/app/features/exceptions/components/exception-stats-page/exception-stats-page.component.ts
- src/app/features/exceptions/components/exception-today-page/exception-today-page.component.html
- src/app/features/exceptions/components/exception-today-page/exception-today-page.component.ts
- src/app/features/exceptions/components/exception-today-stats-page/exception-today-stats-page.component.html
- src/app/features/exceptions/components/exception-today-stats-page/exception-today-stats-page.component.ts
Changed numeration and fixed numeration bug when total pages equal 0
> Changed numeration and fixed numeration

- package-lock.json
- package.json
- src/app/core/services/financialService/financial-statement.service.ts
- src/app/features/financialStatements/Components/financial-statement-result/financial-statement-result.component.html
- src/app/features/financialStatements/Components/financial-statement-result/financial-statement-result.component.ts
- src/app/features/financialStatements/financial-statement.module.ts
need to start with BE_AS_PDF_NewStructure branch
> add pdf to financial statement
